# copyright: 2026 European Union
# license: LICENSE.txt
name: cmts_learn_olci
channels:
  - conda-forge
  - cmts
  - eumetsat
dependencies:
  # Core
  - conda-forge::bokeh
  - conda-forge::cartopy
  - conda-forge::cmocean
  - conda-forge::dask
  - conda-forge::dask-labextension
  - conda-forge::distributed
  - conda-forge::hda
  - conda-forge::ipywidgets
  - conda-forge::jupyterlab
  - conda-forge::matplotlib
  - conda-forge::netcdf4
  - conda-forge::pip
  - conda-forge::python=3.13
  - conda-forge::scikit-image
  - conda-forge::scipy
  - conda-forge::shapely
  - conda-forge::xarray
  - pip:
    - destinelab
  # External
  - cmts::eumartools
  - eumetsat::eumdac
  # Extension
  - conda-forge::copernicusmarine
  # Extension: ThoMaS support
  - conda-forge::beautifulsoup4
  - conda-forge::cdsapi
  - conda-forge::earthaccess
  - conda-forge::ephem
  - conda-forge::pandas
  - conda-forge::urllib3
  - conda-forge::statsmodel
